dropRate:
  BLAZE: "300"
  CHICKEN: "1000"
  HUSK: "300"
  PILLAGER: "300"
  GUARDIAN: "300"
  WITHER_SKELETON: "300"
  RABBIT: "300"
  SPIDER: "300"
  BEE: "300"
  ENDERMAN: "1000"
  FOX: "300"
  TURTLE: "50"
  
  
  
  